это тестовый ноут бук


In [4]:
from datetime import date
date.today()

datetime.date(2025, 12, 21)

In [2]:
import numpy as np
from numpy import linalg
a = np.array([[1,2],[4,2]])
a1  = np.array([[1,2,3],[4,2,6],[1,5,2]]) #создание массива 
b = np.eye(5) #единичиная матрица
np.transpose(a) #транспонирование матриц
c = np.zeros((3,2)) #создание нулевой матрицы
#np.matmul(a,a1)  #перемножение матриц 
#np.dot(a,a1) 
#print(a1)
det = np.linalg.det(a)
#print(a[1,0])   
arr = np.arange(1,100,2)
print(max(arr))

99


Проверка интерпретатора 

In [3]:
import sys
print(f"Версия: {sys.version}")
print(f"Интерпретатор: {sys.implementation.name}")
print(f"Путь: {sys.executable}")

Версия: 3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
Интерпретатор: cpython
Путь: c:\Users\Asus\miniconda3\python.exe


Полезный конспект по numpy

In [11]:
arr = np.array([1,2,5,6,4])
t =np.sum(arr, axis=0) #axis 0 это по столбцам, axis = 1 по строкам, но если одномерный массив то наооброт
p = np.eye(10,10)     
print(np.max(arr, axis=0))
print(p) #первый срез относится к количеству или конкретной строкам (длина столбца),
#второй показывает количество столбцов (длину строки)

6
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
Первое норм подключение к базе данных

In [19]:
import mysql.connector 
dataBase =  mysql.connector.connect(
  host ="localhost",                # Localhost for local connection
  user ="root",
  passwd ="0909egor0909",
  database = "sakila")

cursorObject = dataBase.cursor()
 
query = "select * from actor"
cursorObject.execute(query) 
  
myresult = cursorObject.fetchall() 
for x in myresult:
    print(x)

dataBase.close()

NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported